server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  web:
    resources:
      static-locations: classpath:/templates/,classpath:/static/

mybatis:
  type-aliases-package: cn.edu.guet.springboot.bean
  mapper-locations: classpath:mapper/*Mapper.xml

